<a href="https://colab.research.google.com/github/MarinaMur/Pyda_HW/blob/master/1_%D0%94%D0%97_%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0_%D0%92%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from pymystem3 import Mystem
import re
from numpy import linalg as LA
from sympy import diff
from sympy.abc import x, y
from sympy import *

## Домашнее задание №0 - Основные математические понятия

### Задание 1.

Представить фильмы в виде бинарных векторов (numpy array) используюя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

1. Игра в имитацию [https://www.kinopoisk.ru/film/635772/]
2. Ярость [https://www.kinopoisk.ru/film/740644/]
3. 12 лет рабства [https://www.kinopoisk.ru/film/606646/]
4. Однажды в Голливуде [https://www.kinopoisk.ru/film/1047883/]

In [ ]:
n1 = np.array([0, 0, 0, 0, 1, 0]) #Игра в имитацию
n1

array([0, 0, 0, 0, 1, 0])

In [ ]:
n2 = np.array([0, 1, 0, 1, 0, 0]) #Ярость

In [ ]:
n3 = np.array([0, 0, 1, 0, 1, 0]) #12 лет рабства

In [ ]:
n4 = np.array([0,0,0,1,0,1]) #Однажды в Голливуде

### Задание 2.

Вычислить Евклидову норму каждого из векторов, полученных в Задании 1.

In [ ]:
LA.norm(n1)

1.0

In [ ]:
LA.norm(n2)

1.4142135623730951

In [ ]:
LA.norm(n3)

1.4142135623730951

In [ ]:
LA.norm(n4)

1.4142135623730951

### Задание 3.

Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.  

In [ ]:
n2 = np.array([0, 1, 0, 1, 0, 0]) #Ярость
n3 = np.array([0, 0, 1, 0, 1, 0]) #12 лет рабства
 
numerator = np.dot(n2, n3)
 
n2Len = np.linalg.norm(n2)
n3Len = np.linalg.norm(n3)
 
denominator = n2Len * n3Len
 
# посмотрим, чему равен косинус угла между векторами
cosine = numerator/denominator
cosine

0.0

In [ ]:
angle_radians = np.arccos(cosine)
 

angle_degrees = angle_radians * 360/2/np.pi
angle_degrees

90.0

### Задание 4.

Объединить векторы, полученные в Задании 1 в матрицу, где каждый вектор является строкой матрицы. Полученную матрицу умножить на вектор [1,2,3,4]

In [ ]:
matrix = np.array([n1, n2, n3, n4])
matrix

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1]])

In [ ]:
n5 = np.array([1, 2, 3, 4])
n5

array([1, 2, 3, 4])

In [ ]:
np.dot(n5, matrix)


array([0, 2, 3, 6, 4, 4])

### Задание 5.

Вычислить на бумаге и с помощью Python значение первой и второй производной для функции $3x(x^2+x)^3$ в точке $x=1$

In [ ]:
# руками производная первого порядка будет
# f = 3*x*(x**2+x)**3
# f'(x) = 3((x**2 + x)**3 + 3*x(2*x+1)(x**2 + x)**2) = 21x**6 + 54x**5 + 45x**4 + 12x**3

In [ ]:
# руками производная второго порядка будет
# f = 3((x**2 + x)**3 + 3*x(2*x+1)(x**2 + x)**2)
# f'(x) = 3(3(x(2(x**2+x)**2 + 2(2x+1)**2(x**2+x))+(2x+1)(x**2+x)**2)+3(2x+1)(x**2+x)**2)=126x**5 + 270x**4 + 180x**3 + 36x**2

In [ ]:
x = Symbol('x')

In [ ]:
f = 3*x*(x**2+x)**3

In [ ]:
df_x = f.diff(x)
df_x

3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3

In [ ]:
# значение производной первого порядка в точке x=1
print( df_x.subs( x, 1 ) )

NameError: ignored

In [ ]:
f_y = y.diff(x)
f_y

3*x*(4*x + 2)*(6*x + 3)*(x**2 + x) + 18*x*(x**2 + x)**2 + 6*(6*x + 3)*(x**2 + x)**2

In [ ]:
# значение производной второго порядка в точке x=1
print( f_y.subs( x, 1 ) )

612
